export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  RESTORE = 'RESTORE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  AUTO_ASSIGN = 'AUTO_ASSIGN',
  AUTO_ESCALATE = 'AUTO_ESCALATE',
}
